version: '3'

networks:
  new_bcc:
    external: true
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    expose:
      - "80"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - php
    networks:
      - new_bcc
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html/
    networks:
      - new_bcc

    # --------------------------------------------
    # | 4 : database server
    # --------------------------------------------
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=bccstyle
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=nima
      - MYSQL_PASSWORD=123123
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/data/:/var/lib/mysql"
    networks:
      - new_bcc
  ## --------------------------------------------
  ## | 8 : cache server
  ## --------------------------------------------
  redisdb:
    image: redis:4.0.10-alpine
    expose:
      - "6379"
    volumes:
      - ./docker/redis/default.conf:/usr/local/etc/redis/redis.conf

    ports:
      - 6379:6379
    networks:
      - new_bcc

    ## --------------------------------------------
    ## | 5 : PhpMyAdmin
    ## --------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqldb
    expose:
      - '80'
      - '443'
    environment:
      - PMA_HOST=mysqldb
      - UPLOAD_LIMIT=3000000000
    volumes:
      - /sessions
    ports:
      - 8007:80
    networks:
      - new_bcc
  ## --------------------------------------------
  ## | 9 : Redis Web Client
  ## --------------------------------------------
  phpredisadmin:
    build:
      context: ./docker/phpredisadmin
      dockerfile: Dockerfile
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=redisdb
      - REDIS_1_PORT=6379
    links:
      - redisdb
    expose:
      - "80"
    ports:
      - "1212:80"
    networks:
      - new_bcc

  athena:
    build:
      context: ./docker/athena
      dockerfile: Dockerfile
    ports:
      - "8010:8080"
    env_file:
      - ./docker/athena/.env
    networks:
      - new_bcc